# NAME: Nathan Smith
# EMAIL: nathan.smith@ucla.edu
# ID: 704787554

default: build

build:
	gcc -lmraa -lm -Wall -Wextra -o lab4c_tcp lab4c_tcp.c
	gcc -lssl -lcrypto -Wall -Wextra -o lab4c_tls lab4c_tls.c

# delete all programs and output generated by the Makefile
clean:
	rm -f lab4c_tcp lab4c_tls lab4c-704787554.tar.gz

# (runnable on a Linux desktop or server) create the deliverable tarball
dist: 
	tar -zcvf lab4c-704787554.tar.gz Makefile README lab4c_tcp.c lab4c_tls.c